# -*- coding: utf-8 -*-
"""Copy of sentiment-roberta-pipeline.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Th8RpPCTj6focs92KTtk2x0lZMXibFVI
"""

!pip install transformers

from google.colab import drive

drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/My Drive/Dataset/kickstarter_data_OSF.csv') #Loading our csv from drive

df['blurb'][1:5]

from transformers import pipeline
sentiment_analysis = pipeline("sentiment-analysis",model="siebert/sentiment-roberta-large-english")

print(sentiment_analysis('Hey there, I hate sushi')) #test if model works

#create a loop to test x number of sentences from our data
for i in range(10):
  print(sentiment_analysis(df['blurb'][i]))

#It works!